name: Main

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # zip all files
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: papaplattify.zip
      # create github release
      - name: Release
        uses: softprops/action-gh-release@v1
      # release new version on chrome
      - name: Chrome Extension upload & publish
        uses: Klemensas/chrome-extension-upload-action@1.3
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name: './papaplattify.zip'
          app-id: ${{ secrets.APP_ID }}
          publish: false
  
